// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3p9NtElDwjzQI_nxzgb50hFKL1qeLkk',
    appId: '1:293059584203:web:d70a0f3d1528acb177fb4e',
    messagingSenderId: '293059584203',
    projectId: 'hydratex-cd9d8',
    authDomain: 'hydratex-cd9d8.firebaseapp.com',
    storageBucket: 'hydratex-cd9d8.appspot.com',
    measurementId: 'G-NHJZVJWD3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWF6xpjsnM93BlG29mpT051Qg-p3YtWg',
    appId: '1:293059584203:android:78c37f4a5cbd4c0077fb4e',
    messagingSenderId: '293059584203',
    projectId: 'hydratex-cd9d8',
    storageBucket: 'hydratex-cd9d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aYgh03xC7OVkGaaCx9DI35AY5OtR6hY',
    appId: '1:293059584203:ios:1b640d59fbeb372377fb4e',
    messagingSenderId: '293059584203',
    projectId: 'hydratex-cd9d8',
    storageBucket: 'hydratex-cd9d8.appspot.com',
    iosClientId: '293059584203-8cbv04m6l9mbj5ft3ookg2tcg51fq7i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.watintakeDribbleDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6aYgh03xC7OVkGaaCx9DI35AY5OtR6hY',
    appId: '1:293059584203:ios:1b640d59fbeb372377fb4e',
    messagingSenderId: '293059584203',
    projectId: 'hydratex-cd9d8',
    storageBucket: 'hydratex-cd9d8.appspot.com',
    iosClientId: '293059584203-8cbv04m6l9mbj5ft3ookg2tcg51fq7i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.watintakeDribbleDesign',
  );
}
